In [55]:
import numpy as np

def printer(task, **kwargs):
    print(f'\nTask: {task}')
    for key, value in kwargs.items():
        print(f'\n{key}: {value}')

# task 1
vector = np.arange(1, 11)
printer(1, vector=vector)

#task 2
matrix = np.zeros((3, 3))
printer(2, matrix=matrix)

#task 3
matrix = np.random.randint(1, 11, (5, 5))
printer(3, matrix=matrix)

#task 4
matrix = np.random.random((4, 4))
printer(4, matrix=matrix)

#task 5
vector_1 = np.random.randint(1, 11, 5)
vector_2 = np.random.randint(1, 11, 5)

sum_of_vectors = vector_1 + vector_2
subtraction_of_vectors = vector_1 - vector_2
multiplication_of_vectors = vector_1 * vector_2

printer(5, sum_of_vectors=sum_of_vectors, subtraction_of_vectors=subtraction_of_vectors,
        multiplication_of_vectors=multiplication_of_vectors)
#task 6
vector_1 = np.random.randint(1, 11, 7)
vector_2 = np.random.randint(1, 11, 7)

scalar_product = np.dot(vector_1, vector_2)

printer(6, scalar_product=scalar_product)

#task 7
matrix_1 = np.random.randint(1, 11, (2, 2))
matrix_2 = np.random.randint(1, 11, (2, 3))

matrix = np.dot(matrix_1, matrix_2)

printer(7, matrix=matrix)

#task 8

matrix = np.random.randint(1, 11, (3, 3))
matrix_inverse = np.linalg.inv(matrix)

printer(8, matrix=matrix, matrix_inverse=matrix_inverse)

#task 9

matrix = np.random.random((4,4))
matrix_transposed = matrix.T

printer(9, matrix=matrix, matrix_transposed=matrix_transposed)

# task 10

matrix = np.random.randint(1, 11, (3, 4))
vector = np.random.randint(1, 11, 4)

matrix_multiplied_by_vector = np.dot(matrix, vector)


printer(10, matrix=matrix, vector=vector,
        matrix_multiplied_by_vector=matrix_multiplied_by_vector)

# task 11

matrix = np.random.random((2, 3))
vector = np.random.random(3)

matrix_multiplied_by_vector = np.dot(matrix, vector)

printer(11, matrix=matrix, vector=vector,
        matrix_multiplied_by_vector=matrix_multiplied_by_vector)

# task 12

matrix_1 = np.random.randint(1, 11, (2, 2))
matrix_2 = np.random.randint(1, 11, (2, 2))
multiplied_matrix = matrix_1 * matrix_2

printer(12, matrix_1=matrix_1, matrix_2=matrix_2, multiplied_matrix=multiplied_matrix)

# task 13

matrix_1 = np.random.randint(1, 11, (2, 2))
matrix_2 = np.random.randint(1, 11, (2, 2))

multiplied_matrix = np.dot(matrix_1, matrix_2)

printer(13, matrix_1=matrix_1, matrix_2=matrix_2, multiplied_matrix=multiplied_matrix)

# task 14

matrix = np.random.randint(1, 101, (5, 5))
sum_of_elements = matrix.sum()

printer(14, matrix=matrix, sum_of_elements=sum_of_elements)

#task 15

matrix_1 = np.random.randint(1, 11, (4, 4))
matrix_2 = np.random.randint(1, 11, (4, 4))

subtraction_of_matrices = matrix_1 - matrix_2

printer(15, matrix_1=matrix_1, matrix_2=matrix_2, subtraction_of_matrices=subtraction_of_matrices)

# task 16

matrix = np.random.random((3, 3))
data_for_column_vector = []
for row in matrix:
    sum_of_row = sum(row)
    data_for_column_vector.append(sum_of_row)
column_vector = np.array(data_for_column_vector).reshape(3, 1)

printer(16, matrix=matrix, column_vector=column_vector)

# task 17

matrix = np.random.randint(1, 11, (3, 4))
matrix_squared = matrix ** 2

printer(17, matrix=matrix, matrix_squared=matrix_squared)

# task 18

vector = np.random.randint(1, 51, 4)
vector_sqrt = np.sqrt(vector)

printer(18, vector=vector, vector_sqrt=vector_sqrt)




Task: 1

vector: [ 1  2  3  4  5  6  7  8  9 10]

Task: 2

matrix: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Task: 3

matrix: [[ 2  6  5  6  8]
 [ 5 10  5  8  5]
 [ 3 10  1  2  9]
 [ 3  4  6  3  6]
 [10 10  8  9  4]]

Task: 4

matrix: [[0.82108357 0.30735345 0.75892786 0.31927168]
 [0.3808265  0.08788021 0.51117923 0.74577017]
 [0.93665981 0.86130795 0.28134989 0.29433112]
 [0.42895492 0.71655106 0.3685228  0.90785439]]

Task: 5

sum_of_vectors: [ 6 12  9 10 16]

subtraction_of_vectors: [-4 -8 -3 -6 -4]

multiplication_of_vectors: [ 5 20 18 16 60]

Task: 6

scalar_product: 227

Task: 7

matrix: [[28 39 25]
 [75 56 76]]

Task: 8

matrix: [[10  2 10]
 [ 4 10  9]
 [10  4  5]]

matrix_inverse: [[-0.025      -0.05357143  0.14642857]
 [-0.125       0.08928571  0.08928571]
 [ 0.15        0.03571429 -0.16428571]]

Task: 9

matrix: [[0.27743714 0.45116213 0.40739336 0.70085384]
 [0.45656653 0.33154678 0.33727969 0.83150352]
 [0.80760719 0.35459414 0.44076813 0.0568856 ]
 [0.45526242 0.71250695 0.6